/**
 * VERSION Streetwear — Product Catalog
 * Add new products by pushing objects to this array.
 */

const SITE = {
  tiktok: "https://www.tiktok.com/@vrsnstreetwear",
  instagram: "https://www.instagram.com/version.streetwear",
  facebook: "https://www.facebook.com/vrsn.street",
  email: "version.est2026@gmail.com",
  shopComingSoon: true,
};

const PRODUCTS = [
  {
    id: "afterglow",
    name: "Afterglow",
    description: "Soft-toned graphic with a cinematic fade. Boxy fit, DTF print on premium cotton.",
    price: 899,
    image: "Products/Afterglow 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: false,
  },
  {
    id: "aquarius",
    name: "Aquarius",
    description: "Zodiac series drop. Bold constellation graphic on oversized silhouette.",
    price: 899,
    image: "Products/AQUARIUS 4.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: false,
  },
  {
    id: "aries",
    name: "Aries",
    description: "Fire sign energy. Sharp zodiac artwork with clean streetwear lines.",
    price: 899,
    image: "Products/ARIES 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "ascent",
    name: "Ascent",
    description: "Rise above the noise. Minimal graphic with maximum impact.",
    price: 899,
    image: "Products/ASCENT 1.webp",
    category: "boxy-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: true,
  },
  {
    id: "better-days",
    name: "Better Days",
    description: "Optimistic streetwear staple. Relaxed boxy cut for everyday wear.",
    price: 899,
    image: "Products/Better days 1.webp",
    category: "boxy-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: false,
  },
  {
    id: "capricorn",
    name: "Capricorn",
    description: "Earth sign precision. Structured graphic on heavyweight tee.",
    price: 899,
    image: "Products/CAPRICORN 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "capture",
    name: "Capture",
    description: "Freeze the moment. Urban photography-inspired graphic tee.",
    price: 899,
    image: "Products/Capture 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "cathedral",
    name: "Cathedral",
    description: "Architectural lines meet street culture. Statement oversized piece.",
    price: 949,
    image: "Products/Cathedral 1.webp",
    category: "oversized-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: true,
  },
  {
    id: "dad-mode",
    name: "Dad Mode",
    description: "Ironically cool. Relaxed fit graphic for the culture.",
    price: 899,
    image: "Products/Dad Mode 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "daydream",
    name: "Daydream",
    description: "Soft surreal graphic. Dream-state aesthetic on boxy cotton.",
    price: 899,
    image: "Products/Daydream 1.webp",
    category: "oversized-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "dream",
    name: "Dream",
    description: "Visionary artwork. Premium DTF print with lasting detail.",
    price: 899,
    image: "Products/Dream 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "ferrari",
    name: "Ferrari",
    description: "Motorsport-inspired graphic. Speed and style in one drop.",
    price: 949,
    image: "Products/Ferrari.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: false,
  },
  {
    id: "flashback",
    name: "Flashback",
    description: "Retro energy, modern cut. Nostalgia-driven streetwear piece.",
    price: 899,
    image: "Products/Flashback 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "ford",
    name: "Ford",
    description: "Classic automotive graphic. Built for the streets.",
    price: 949,
    image: "Products/Ford 4.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "gemini",
    name: "Gemini",
    description: "Dual nature zodiac drop. Twin-inspired artwork on boxy tee.",
    price: 899,
    image: "Products/GEMINI 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "halo",
    name: "Halo",
    description: "Elevated minimal graphic. Clean lines, bold presence.",
    price: 899,
    image: "Products/Halo 1.webp",
    category: "boxy-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: true,
  },
  {
    id: "lambo",
    name: "Lambo",
    description: "Supercar silhouette. High-impact motorsport streetwear.",
    price: 949,
    image: "Products/Lambo 4.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: false,
  },
  {
    id: "leo",
    name: "Leo",
    description: "Lion energy zodiac piece. Regal graphic on premium cotton.",
    price: 899,
    image: "Products/LEO 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "libra",
    name: "Libra",
    description: "Balance and style. Zodiac series with refined artwork.",
    price: 899,
    image: "Products/LIBRA 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "mup-both",
    name: "MUP Both",
    description: "Dual-sided concept graphic. Standout boxy fit essential.",
    price: 899,
    image: "Products/MUP-BOTH B.webp",
    category: "boxy-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: true,
  },
  {
    id: "my",
    name: "MY",
    description: "Personal statement piece. Minimal branding, maximum attitude.",
    price: 899,
    image: "Products/MY 1.webp",
    category: "boxy-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "night-run",
    name: "Night Run",
    description: "After-dark aesthetic. Urban nightscape graphic tee.",
    price: 899,
    image: "Products/Night run 3.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: true,
  },
  {
    id: "pisces",
    name: "Pisces",
    description: "Water sign flow. Dreamy zodiac artwork on oversized cut.",
    price: 899,
    image: "Products/PISCES 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "playbook",
    name: "Playbook",
    description: "Strategy meets style. Sport-inspired streetwear graphic.",
    price: 899,
    image: "Products/Playbook 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "porsche",
    name: "Porsche",
    description: "Precision engineering aesthetic. Motorsport graphic drop.",
    price: 949,
    image: "Products/Porsche 4.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "pulse",
    name: "Pulse",
    description: "Heartbeat of the city. Dynamic graphic on boxy silhouette.",
    price: 899,
    image: "Products/Pulse 2.webp",
    category: "oversized-shirt",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "rose",
    name: "Rose",
    description: "Floral edge meets streetwear. Bold contrast graphic tee.",
    price: 899,
    image: "Products/Rose.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "sagittarius",
    name: "Sagittarius",
    description: "Archer zodiac drop. Adventure-ready streetwear graphic.",
    price: 899,
    image: "Products/SAGGITARIUS 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "scorpio",
    name: "Scorpio",
    description: "Intense zodiac energy. Dark aesthetic on boxy fit.",
    price: 899,
    image: "Products/SCORPIO 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "spring",
    name: "Spring",
    description: "Seasonal drop energy. Fresh graphic on premium cotton.",
    price: 899,
    image: "Products/Spring 2.webp",
    category: "new-release",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: true,
  },
  {
    id: "taurus",
    name: "Taurus",
    description: "Grounded zodiac piece. Strong bull motif on boxy tee.",
    price: 899,
    image: "Products/TAURUS 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "train",
    name: "Train",
    description: "Motion and momentum. Urban transit-inspired graphic.",
    price: 899,
    image: "Products/Train 1.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
  {
    id: "v1",
    name: "V1",
    description: "The original VERSION drop. Signature brand graphic tee.",
    price: 949,
    image: "Products/v1 4.webp",
    category: "new-release",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: true,
    isNew: true,
  },
  {
    id: "virgo",
    name: "Virgo",
    description: "Detail-driven zodiac artwork. Clean precision on boxy fit.",
    price: 899,
    image: "Products/VIRGO 2.webp",
    category: "graphic-tee",
    tags: ["Boxy Fit", "DTF Print", "Streetwear Essential"],
    featured: false,
    isNew: false,
  },
];

const CATEGORIES = [
  { id: "all", label: "All" },
  { id: "boxy-shirt", label: "Boxy Shirt" },
  { id: "oversized-shirt", label: "Oversized Shirt" },
  { id: "graphic-tee", label: "Graphic Tee" },
  { id: "new-release", label: "New Release" },
];

const SIZES = ["S", "M", "L", "XL", "2XL", "3XL"];

const COMING_SOON = [
  {
    name: "VERSION Core Drop",
    description: "Essential monochrome pieces. Launching soon.",
    date: "Coming 2026",
  },
  {
    name: "Zodiac Vol. 2",
    description: "Next chapter of the constellation series.",
    date: "Coming Soon",
  },
  {
    name: "Motorsport Collab",
    description: "Limited automotive-inspired capsule.",
    date: "TBA",
  },
];
